Switch to current_thread tokio::test to fix macOS builds in CI
There seem to be some spurious I/O errors on macOS beta toolchain builds
lately which are causing error messages similar to the one below to
display during test runs:

```
Error: thread 'service::tests::initializes_only_once' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/service.rs:196:66
```

Likewise, 1.52.1 stable appears to be affected as well.

It seems that switching to `#[tokio::test(flavor = "current_thread")]`
everywhere resolves these issues, so perhaps there is a regression in
`tokio` somewhere on macOS? At least this unblocks CI.