Change minimum Rust version to 1.51.0
This is required for const fn `char::to_ascii_lowercase` in `lsp-types`:

```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-types-0.92.0/src/lib.rs:49:26
   |
49 |             buf[buf_i] = rest.to_ascii_lowercase();
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0015`.
error: could not compile `lsp-types`
```